name: Gobrew Build an publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v0.1.*'

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  build:

    runs-on: self-hosted
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:

        # - name: Print current directory
        #   run: pwd

        # - name: Publish files to Github Release
        #   run: goreleaser release --clean

        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: git fetch --force --tags
        - uses: actions/setup-go@v4
          with:
            go-version: stable
        # More assembly might be required: Docker logins, GPG, etc. It all depends
        # on your needs.

        - name: Get latest tag
          id: latest_tag
          run: |
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "::set-output name=tag::$LATEST_TAG"

        # Extract the numeric part of the tag and increment it
        - name: Determine next tag
          id: next_tag
          run: |
            TAG=${{ steps.latest_tag.outputs.tag }}
            NEXT_TAG=v0.1.$((10#${TAG#"v0.1."} + 1))
            echo "::set-output name=tag::$NEXT_TAG"

        - name: Tag release
          run: |
            git tag ${{ steps.next_tag.outputs.tag }}
            git push origin ${{ steps.next_tag.outputs.tag }}

        - uses: goreleaser/goreleaser-action@v4
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro':
            distribution: goreleaser
            version: latest
            args: release --clean