name: Gobrew Build an publish

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    steps:

        - name: Publish files to Github Release
          run: goreleaser release --clean