name: Gobrew Build an publish

on:
  # push:
  #   branches: [ main ]
  #   tags:
  #     - 'v0.2.0'
  pull_request:
    branches: [ main ]
    types:
      - closed

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  build:

    runs-on: self-hosted
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    if: ${{ github.event.pull_request.merged == true }}
    steps:

        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: git fetch --force --tags
        - uses: actions/setup-go@v4
          with:
            go-version: stable
        # More assembly might be required: Docker logins, GPG, etc. It all depends
        # on your needs.

        - name: Tag release
          run: git tag v0.2.${{ github.run_number }}

        - uses: goreleaser/goreleaser-action@v4
          with:
            # either 'goreleaser' (default) or 'goreleaser-pro':
            distribution: goreleaser
            version: latest
            args: release --clean